function results = myimagesresizefcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------


im = imresize(im,[28 NaN]);

% imgray = im2gray(im);
% 
% bw = imbinarize(imgray);
% 
% results.imgray = imgray;
% results.bw     = bw;


results.im =im;



%--------------------------------------------------------------------------
